version: '3.9' # optional since v1.27.0
services:
  docker-frontend:
    build:
      context: UI
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - ./UI/src:/frontend/src